name: Deploy mobile to Preview

jobs:
  fingerprint:
    name: Fingerprint Preview app
    type: fingerprint
    environment: preview

  get_android_build:
    name: Find compatible Preview Android build
    needs: [fingerprint]
    type: get-build
    params:
      platform: android
      profile: preview
      channel: preview
      fingerprint_hash: ${{ needs.fingerprint.outputs.android_fingerprint_hash }}
      wait_for_in_progress: true

  build_android:
    name: Build Preview Android app
    needs: [get_android_build]
    if: ${{ !needs.get_android_build.outputs.build_id }}
    type: build
    params:
      platform: android
      profile: preview

  update_android:
    name: Publish Preview Android OTA update
    needs: [get_android_build]
    if: ${{ needs.get_android_build.outputs.build_id }}
    type: update
    environment: preview
    params:
      channel: preview
      platform: android
