name: Deploy mobile to production

jobs:
  fingerprint:
    name: Fingerprint Production app
    type: fingerprint
    environment: production

  get_android_build:
    name: Find compatible Production Android build
    needs: [fingerprint]
    type: get-build
    params:
      platform: android
      profile: production-apk
      channel: production
      fingerprint_hash: ${{ needs.fingerprint.outputs.android_fingerprint_hash }}
      wait_for_in_progress: true

  build_android:
    name: Build Production Android app
    needs: [get_android_build]
    if: ${{ !needs.get_android_build.outputs.build_id }}
    type: build
    params:
      platform: android
      profile: production-apk

  update_android:
    name: Publish Production Android OTA update
    needs: [get_android_build]
    if: ${{ needs.get_android_build.outputs.build_id }}
    type: update
    environment: production
    params:
      channel: production
      platform: android
