import type { SellerRanking, SellerRankingQuery } from './types';
import { getRankingTrend } from './types';

const thumbnail = (id: string, label: string): { id: string; imageUrl: null; label: string; groupBuyId: string } => ({
  id,
  imageUrl: null,
  label,
  groupBuyId: `group-${id}`,
});

export const MOCK_RANKINGS: SellerRanking[] = [
  {
    id: 'rank-1',
    sellerId: 'seller-ovenfresh',
    rank: 1,
    previousRank: 4,
    trend: getRankingTrend(1, 4),
    displayName: '오븐프레시 마켓',
    username: 'ovenfresh.market',
    avatarUrl: null,
    category: 'food',
    followerCount: 48200,
    activeDealCount: 12,
    endingSoonCount: 3,
    trustScore: 98,
    isFollowing: true,
    isSponsored: false,
    thumbnails: [thumbnail('oven-1', '그래놀라'), thumbnail('oven-2', '무화과잼'), thumbnail('oven-3', '버터쿠키')],
    representativeGroupBuyId: 'group-oven-1',
  },
  {
    id: 'rank-2',
    sellerId: 'seller-mellowmom',
    rank: 2,
    previousRank: 1,
    trend: getRankingTrend(2, 1),
    displayName: '멜로우맘 키즈',
    username: 'mellowmom.kids',
    avatarUrl: null,
    category: 'baby',
    followerCount: 31500,
    activeDealCount: 8,
    endingSoonCount: 2,
    trustScore: 95,
    isFollowing: false,
    isSponsored: false,
    thumbnails: [thumbnail('mom-1', '등원룩'), thumbnail('mom-2', '간식팩'), thumbnail('mom-3', '세제')],
    representativeGroupBuyId: 'group-mom-1',
  },
  {
    id: 'rank-3',
    sellerId: 'seller-glowpick',
    rank: 3,
    previousRank: null,
    trend: getRankingTrend(3, null),
    displayName: '글로우픽 뷰티',
    username: 'glowpick.beauty',
    avatarUrl: null,
    category: 'beauty',
    followerCount: 62100,
    activeDealCount: 15,
    endingSoonCount: 5,
    trustScore: 96,
    isFollowing: false,
    isSponsored: true,
    thumbnails: [thumbnail('glow-1', '비타세럼'), thumbnail('glow-2', '선쿠션'), thumbnail('glow-3', '클렌저')],
    representativeGroupBuyId: 'group-glow-1',
  },
  {
    id: 'rank-4',
    sellerId: 'seller-studiofit',
    rank: 4,
    previousRank: 4,
    trend: getRankingTrend(4, 4),
    displayName: '스튜디오핏',
    username: 'studiofit.daily',
    avatarUrl: null,
    category: 'fashion',
    followerCount: 27700,
    activeDealCount: 6,
    endingSoonCount: 1,
    trustScore: 91,
    isFollowing: true,
    isSponsored: false,
    thumbnails: [thumbnail('fit-1', '니트'), thumbnail('fit-2', '코트')],
    representativeGroupBuyId: 'group-fit-1',
  },
  {
    id: 'rank-5',
    sellerId: 'seller-livingnote',
    rank: 5,
    previousRank: 9,
    trend: getRankingTrend(5, 9),
    displayName: '리빙노트',
    username: 'livingnote.home',
    avatarUrl: null,
    category: 'lifestyle',
    followerCount: 39800,
    activeDealCount: 10,
    endingSoonCount: 4,
    trustScore: 93,
    isFollowing: false,
    isSponsored: false,
    thumbnails: [thumbnail('living-1', '수납함'), thumbnail('living-2', '디퓨저'), thumbnail('living-3', '침구')],
    representativeGroupBuyId: 'group-living-1',
  },
  {
    id: 'rank-6',
    sellerId: 'seller-techpick',
    rank: 6,
    previousRank: 5,
    trend: getRankingTrend(6, 5),
    displayName: '테크픽 공구',
    username: 'techpick.gadget',
    avatarUrl: null,
    category: 'digital',
    followerCount: 18200,
    activeDealCount: 4,
    endingSoonCount: 0,
    trustScore: 89,
    isFollowing: false,
    isSponsored: false,
    thumbnails: [thumbnail('tech-1', '충전기'), thumbnail('tech-2', '키보드'), thumbnail('tech-3', '허브')],
    representativeGroupBuyId: 'group-tech-1',
  },
];

export const MOCK_QUERY: SellerRankingQuery = {
  tab: 'ranking',
  category: 'all',
  period: 'weekly',
  sort: 'popular',
};
